language: node_js
before_script:
  - npm install -g @vue/cli-service
node_js:
  - "10"
deploy:
  provider: script
  script: npm install && npm run lint
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
  - node_modules
